# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 04:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='data',
            new_name='data_used',
        ),
    ]
