# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 05:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0003_auto_20160118_0512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='data_used',
            new_name='data_left',
        ),
    ]
